"""empty message

Revision ID: ca2b0b9c9948
Revises: 86c9b06e766e
Create Date: 2023-05-17 00:06:57.764903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2b0b9c9948'
down_revision = '86c9b06e766e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('favorites_character_id', sa.Integer(), nullable=True),
    sa.Column('favorites_planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['favorites_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['favorites_planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
